services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - .:/app:cached
      - /app/vendor
      - /app/node_modules
    environment:
      - APP_ENV=production
      - APP_DEBUG=true
      - APP_KEY=base64:ZsVq7IAnNOtsRmKVe4WeBsiK8sueZ/2W4wnJpEDohMk=
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    depends_on:
      - db
      - node

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node-app
    ports:
      - "5173:5173"
    volumes:
      - ./public:/app/public:cached
      - ./resources:/app/resources:cached
      - ./vite.config.js:/app/vite.config.js:cached
    environment:
      - NODE_OPTIONS=--max-old-space-size=2048
    command: npm run build

  db:
    image: postgres:13
    container_name: laravel-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data:cached

  python:
    build:
      context: .
      dockerfile: python.dockerfile
    image: python:3.11.3
    container_name: python-app
    working_dir: /usr/src/app
    volumes:
      - ./python:/app/python
      - ./python/dumps:/app/python/dumps
      - .:/app:cached
      - ./python:/usr/src/app:cached
    command: sh -c "pip install -r requirements.txt && tail -f /dev/null"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data:
    driver: local
  node_modules:
    driver: local
