# Use a Node.js image
FROM node:20.3.0

# Set the working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Clear npm cache and remove existing node_modules
RUN rm -rf node_modules package-lock.json

# Clean npm cache
RUN npm cache clean --force

# Install dependencies
RUN npm ci

# Copy the rest of your application code
COPY . .

# Expose the port your app runs on
EXPOSE 3000

# Run the development server
CMD ["npm", "run", "dev"] 